name: CI Pipeline (UAS Backend)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies (User Service)
      run: |
        cd user-service
        npm install

    - name: Build Aplikasi (User Service)
      run: |
        cd user-service
        npm run build

    - name: Unit Test (User Service)
      run: |
        cd user-service
        npm run test -- --pass-with-no-tests

    - name: Install Dependencies (Order Service)
      run: |
        cd order-service
        npm install

    - name: Build Aplikasi (Order Service)
      run: |
        cd order-service
        npm run build

    - name: Unit Test (Order Service)
      run: |
        cd order-service
        npm run test -- --pass-with-no-tests